# Generated by Django 5.1.6 on 2025-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('usage_instructions', models.TextField()),
                ('side_effects', models.TextField()),
                ('prescription_required', models.BooleanField()),
                ('expiry_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
