# Generated by Django 5.1.6 on 2025-02-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
