# Generated by Django 5.1.6 on 2025-02-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0009_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
