# Generated by Django 5.1.6 on 2025-02-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0010_remove_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_count',
        ),
    ]
