# Generated by Django 5.1.5 on 2025-02-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicare', '0015_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('product', 'type')},
        ),
    ]
